version: "3.5"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password1234"
      POSTGRES_DB: "guitar-shop"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d password1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ${POSTGRES_DB_DIR:-../../../db}:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "password1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8082:80"
    restart: unless-stopped
    networks:
      - postgres

  fakesmtp:
    image: gessnerfl/fake-smtp-server:1.10.4
    container_name: fakesmtp
    ports:
      - 5025:5025
      - 1083:5080

networks:
  postgres:
    driver: bridge
